### ISSUE TITLE
Unexpected, frequent timeout 

### ISSUE THREAD

**Issue by realliyifei** [danielnsilva/semanticscholar#74]
The timeout happens frequently. My current walk around is to enforce running up to three times.

Is this expected? Could you help me a bit?

```
Traceback (most recent call last):
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/anyio/streams/tls.py", line 133, in _call_sslobject_method
    result = func(*args)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/ssl.py", line 889, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2633)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/anyio/streams/tls.py", line 198, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1095, in receive
    await self._protocol.read_event.wait()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/asyncio/futures.py", line 196, in result
    raise exc
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f709761e580

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 36, in read
    return b""
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
    data = await self._network_stream.read(
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 36, in read
    return b""
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/nlpgridio3/data/liyifei/survey-generation-dev/src/generate_refs.py", line 54, in <module>
    generate_refs('test')
  File "/mnt/nlpgridio3/data/liyifei/survey-generation-dev/src/generate_refs.py", line 26, in generate_refs
    results = sch.search_paper(ref_title)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/semanticscholar/SemanticScholar.py", line 266, in search_paper
    results = loop.run_until_complete(
  File "/home1/l/liyifei/.local/lib/python3.9/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/semanticscholar/AsyncSemanticScholar.py", line 342, in search_paper
    results = await PaginatedResults.create(
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/semanticscholar/PaginatedResults.py", line 56, in create
    await obj._async_get_next_page()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/semanticscholar/PaginatedResults.py", line 121, in _async_get_next_page
    results = await self._request_data()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/semanticscholar/PaginatedResults.py", line 112, in _request_data
    return await self._requester.get_data_async(
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/semanticscholar/ApiRequester.py", line 62, in get_data_async
    r = await client.request(
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/nlp/data/liyifei/.conda/envs/lsg/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
```

**Comment by danielnsilva** [comment]
Have you tried increasing the timeout?

```python
from semanticscholar import SemanticScholar
sch = SemanticScholar(timeout=30)
```

**Comment by danielnsilva** [comment]
Closing this issue for now. Please reopen if you have further questions.
